### ISSUE TITLE
Add support for quick rolls on ability and skill checks

### ISSUE THREAD

**Issue by cs96and** [slcao2/FoundryVTT-QuickRolls#19]
It would be nice to use Quick Rolls for ability and skill checks.

Also, could you add support so you can click on the ability/save modifier numbers to roll the correct thing without having to choose between them in a dialog box.

**Comment by slcao2** [comment]
In terms of functionality, you're thinking something like clicking the button autorolls the check as a standard roll with the advantage/disadvantage buttons in the card? For the skill checks, since you can hotkey them directly using SHIFT/CTRL/ALT click and it's just a simple roll and not linked to anything necessarily, it seems like it might not be too useful.

On the second point, I would suggest using the [Tidy5e Sheet](https://github.com/sdenec/tidy5e-sheet) module as it provides close to what you might be looking for. I'm hesitant to override the buttons as they may conflict with the various sheets that are out there.

I'll look into it a bit but this wouldn't be a priority for me in terms of features. Thanks for bringing the suggestion!

**Comment by cs96and** [comment]
Sorry replied to wrong issue.  Please re-open the issue.

**Comment by cs96and** [comment]
Yes I was thinking it would basically behave the same as a weapon attack, where it would auto roll without an extra dialog box.  It would also show the advantage/disadvantage button in the chat like attack rolls.  Obviously, there would not be a damage button though.

>  For the skill checks, since you can hotkey them directly using SHIFT/CTRL/ALT click and it's just a simple roll and not linked to anything necessarily, it seems like it might not be too useful.

For me, I would just like the consistency between ability/skill checks and attack rolls.  And I like the (dis)advantage button that quick rolls throws into the chat.

**Comment by cs96and** [comment]
Any more thoughts on this?  I ran my first game with Quick Rolls instead of Better Rolls last night and my players were confused why ability/skill rolls did not give them the same chat box interface as attack rolls.

**Comment by slcao2** [comment]
Hmm my main concern is still with the additional upkeep that would be required to have it remain parity with the dnd5e system in the event of any changes there as well as different sheet compatibilities but I can maybe take a stab at it and see how much extra work and difficulty it would create. I'll probably be on a mini hiatus unless something game breaking occurs so I probably won't get to it in the near near future.

**Comment by slcao2** [comment]
@cs96and Feature should be implemented. Give it a try!

**Comment by cs96and** [comment]
Excellent work thanks!  I may have another feature request for you related to this though.  However, it may be resolved in core foundry and DAE, so I'll leave it for now.
